### ISSUE TITLE
Tabbar(image tools) is missing when CLImageEditor initialised (swift 1.2)

### ISSUE THREAD

**Issue by gokhandilek** [yackle/CLImageEditor#101]
So i have an edit button to fire the editor in myUIViewController: 

    @IBAction func editImage(sender: AnyObject) {
       let editor = CLImageEditor(image: singleView.image, delegate: self)
        
        self.presentViewController(editor, animated: true, completion: nil)
        
    }

It initialises the editor window(I can see the cancel and the done buttons as well as the single image).

The cancel button and the done button works(it takes me back to myUIViewController)

I am not sure why I am missing the tab bar image tools in this view.

Could you please let me know the possible cause of this?

Thank you and much appreciated.

**Comment by yackle** [comment]
I couldn't reproduce it. Do you have any more informations? Is it happen on all iOS versions or devices?

**Comment by gokhandilek** [comment]
I am using ios 8.3 xcode 6.3

**Comment by gokhandilek** [comment]
Found the problem is actually with IQkeyboardManager...

**Comment by MarkYuan** [comment]
check your UIVIew category
