### ISSUE TITLE
Update for use_frameworks! CocoaPods feature

### ISSUE THREAD

**Issue by andrew8712** [yackle/CLImageEditor#102]
Hey, thanks for the great library! Do you have any plans to update it to support use_frameworks! feature from CocoaPods? Right now it crashes when I try to instantiate CLImageEditor, because you use [NSBundle mainBundle] in CLImageEditorTheme (frameworks require to use [NSBundle bundleForClass:[self class]]). There are other issues with missing images, I believe they related to NSBundle issue as well.

**Comment by yackle** [comment]
I'll try. Please wait.

**Comment by yackle** [comment]
It is probably fixed. Could you check:

```
pod 'CLImageEditor', :git => 'https://github.com/yackle/CLImageEditor', :branch => "develop"
```

**Comment by andrew8712** [comment]
Seems working! Big thanks. When will you merge the branches?

**Comment by yackle** [comment]
merged, thanks!
