### ISSUE TITLE
Crash with big image

### ISSUE THREAD

**Issue by Tippit** [yackle/CLImageEditor#103]
The App crash with a big image ex: 8000x8000 16.44MB RGB 72x72. Could you tell me what is the maximum image size the editor can handle?
For this sample most of Photo Editor (Enlight, Afterlight) downscale the res to 4096x4096, is there a way to do something equivalent to avoid a crash?

**Comment by yackle** [comment]
I don't know, and I never thought about such a large image. Let me suggest that you pass a downscaled image to the editor.

**Comment by Tippit** [comment]
Thank's Yackle :)

Cordialement,
Claude Bezeaud.
