### ISSUE TITLE
Can't change Status bar color to light content?

### ISSUE THREAD

**Issue by Rjmaurya13** [yackle/CLImageEditor#104]
I want to change status bar color to light content but it doesn't chnage.

**Comment by yackle** [comment]
How about http://stackoverflow.com/a/18184831

**Comment by yackle** [comment]
Or check out develop branch, and try

```
[[CLImageEditorTheme theme] setStatusBarStyle:UIStatusBarStyleLightContent];
```

**Comment by Rjmaurya13** [comment]
Thanks. I am using a custom navigation bar to change left and right button image. On every new launch status will not change to light content. After coming back from sub tool will update status bar to light content and after that remain same.

**Comment by yackle** [comment]
Sorry, I cannot understand what is the real issue. What are you tried?
