### ISSUE TITLE
Setting custom icons is broken in 0.1.4

### ISSUE THREAD

**Issue by fraserscottmorrison** [yackle/CLImageEditor#107]
The following was working in 0.1.3 but broken in 0.1.4
```  objc
CLImageToolInfo *tool = [editor.toolInfo subToolInfoWithToolName:@"CLToneCurveTool" recursive:NO];
tool.iconImagePath = @"test.png";
```
If I try to set a custom icon, then no icon is shown

**Comment by fraserscottmorrison** [comment]
Ok it seems like you've changed the initialisation of the icons from imageNamed to fastImageWithContentsOfFile and I just needed to use an absolute path.

Perhaps you should just update the readme so show how to set it now:
```
filterTool.iconImagePath = [[NSBundle mainBundle] pathForResource:@"icn_photo_filter" ofType:@"png"];
```

**Comment by yackle** [comment]
Updated. thx!

**Comment by fraserscottmorrison** [comment]
No prob. I submitted a little pull request too
Fraser
