### ISSUE TITLE
How to handle touch events

### ISSUE THREAD

**Issue by Tippit** [yackle/CLImageEditor#113]
Hi,

I would like to handle finger move on the screen (Touch event) to update the inputCenter parameter of some effects.

I don't know how to do, can you help me or give some advices please!

Example with sliders     [filter setValue:[NSNumber numberWithFloat:_scaleSlider.value] forKey:@"inputScale"];
when you change slider position the image reflect change, is it possible to do the same with one figer slide on screen?

**Comment by yackle** [comment]
I'm not sure you want to do. But I think that CLSpotEffect would be helpful.

**Comment by Tippit** [comment]
actually for some effects I have wanted to use the swipe of a finger to change the values ​​instead of sliders.

and I am also move the focus of certain effects (property "inputCenter") in the same way.

Best regards,
Claude Bezeaud.

**Comment by yackle** [comment]
sorry, i cannot understand.

**Comment by Tippit** [comment]
it does not matter i Will try with CLSpotEffect. Thank you for advice :)

Best regards,
Claude Bezeaud.
