### ISSUE TITLE
Open UIImagePickerController from EffectTool Toolbar

### ISSUE THREAD

**Issue by Tippit** [yackle/CLImageEditor#114]
Hi,

From CLEffectTool I use filters category GPUImageDissolveBlendFilter from GPUImage (I need the sliders for minxing two images) I would like the user to choose an image from its library to use as a filter overlay. how to open UIImagePickerController from the toolbar?

Regards.

**Comment by yackle** [comment]
You should to add a button or a toolbar by yourself.

**Comment by Tippit** [comment]
Ok from where could i make a call to UIImagePickerController, setup or applyEfect? 

Best regards,
Claude Bezeaud.

**Comment by Tippit** [comment]
in fact I do not know how to handle the event when the user press the button  to make a call to UIImagePickerController

Best regards,
Claude Bezeaud.

**Comment by yackle** [comment]
Do you mean that you want to know how to use the UIButton?

**Comment by Tippit** [comment]
I want to know where i can make the call to UIImagePickerController, CLEffectTool , setup or applyEfect ?

Best regards,
Claude Bezeaud.

**Comment by Tippit** [comment]
the answer should be simple I'll get some more. sorry for the inconvenience

**Comment by Tippit** [comment]
Currently I created a blend effect with the wrapper library GPUImage, I offer filter images from my toolbar (it is in the bundle file) but I want to load an image from my photo album rather than the bundle. 

In other words you have an image in the editor and you want to add a second image from your photo album, I like to know how to add this second picture after having created a button for this feature

**Comment by yackle** [comment]
And so did you try what code?

**Comment by Tippit** [comment]
my toolbar contains only one button to call

UIAlertController alertController * = [UIAlertController alertControllerWithTitle: nil message: nil preferredStyle: UIAlertControllerStyleActionSheet];
 
I placed in - (UIImage *) applyEffect: (UIImage *) Image :-(

**Comment by yackle** [comment]
So what is the problem? How do it become if you try changing to setup?

**Comment by Tippit** [comment]
Thank's Yackle :)

Best regards,
Claude Bezeaud.
