### ISSUE TITLE
Load image from album

### ISSUE THREAD

**Issue by Tippit** [yackle/CLImageEditor#115]
hi,

I return to my previous question regarding the use of "UIImagePickerController"
I use "CLEffectTool" to apply a "GPUImageDissolveBlendFilter" filter on the image in the editor.

This filter requires me to provide an additional image (overlay) I wish to load it from my photo album, so I need to use UIImagePickerController instead of Bundle.

I can not find any place I have to call UIImagePickerController and then recover the selected image for use in my filter.

Here is a sample code in my customEffect.m : 

- (UIImage*)applyEffect:(UIImage*)image
{
    inputImage = [UIImage imageNamed:@"Colorful_24.jpg"];
//// I will wish that inputImage comes from my photo album

    GPUImagePicture *imageSource = [[GPUImagePicture alloc] initWithImage:image];
    [imageSource processImage];
    
    GPUImageDissolveBlendFilter *blendFilter = [[GPUImageDissolveBlendFilter alloc]init];
     GPUImageExposureFilter *brightNessFilter = [[GPUImageExposureFilter alloc] init];
    GPUImageContrastFilter *contrastFilter = [[GPUImageContrastFilter alloc] init];
    
    [(GPUImageDissolveBlendFilter *)blendFilter setMix:_radiusSlider.value];
    [(GPUImageExposureFilter *)brightNessFilter setExposure:_brightnessSlider.value];
    [(GPUImageContrastFilter *)contrastFilter setContrast:_contrastSlider.value];
 
    [imageSource addTarget:blendFilter];
    [imageSource addTarget:brightNessFilter];
    [imageSource addTarget:contrastFilter];
    [imageSource processImage];
    
    UIImage *quickFilteredImage1 = [blendFilter imageByFilteringImage:inputImage];
    UIImage *quickFilteredImage2 = [brightNessFilter imageByFilteringImage:quickFilteredImage1 ];
    UIImage *quickFilteredImage = [contrastFilter imageByFilteringImage:quickFilteredImage2 ];
    
    [imageSource removeAllTargets];
    
    imageSource = nil;
    blendFilter = nil;
    brightNessFilter = nil;
    contrastFilter = nil;
    
    return quickFilteredImage;  
}

Could you help me with some advice or with some sample code I am beginner and I'm struggling to find the right method, thank you in advance for your attention

**Comment by yackle** [comment]
I asked this before as well, how do it become if you try changing to setup?

**Comment by Tippit** [comment]
ok I still try and tell you, thank's

**Comment by Tippit** [comment]
UIImagePickerController in setup it's ok,  so   _blendImage = [info objectForKey:UIImagePickerControllerOriginalImage]; 

_blendImage declared as @property (nonatomic, strong)  UIImage *_blendImage; in CLEffectTool


how to pass _blendImage to  (UIImage*)applyEffect:(UIImage*)image
in CLCustomEffectTool

**Comment by yackle** [comment]
I think it's not my issue. It is totally up to you. But if it were me I'd probably do it below.

```
- (id)initWithSuperView:(UIView*)superview imageViewFrame:(CGRect)frame toolInfo:(CLImageToolInfo*)info
{
    self = [super initWithSuperView:superview imageViewFrame:frame toolInfo:info];
    if(self){
        // The rest of your method implementation.

        UIImagePickerController *picker = [[UIImagePickerController alloc] init];
        UIViewController *vc = [[[UIApplication sharedApplication] keyWindow] rootViewController];
        while (vc.presentedViewController) { vc = vc.presentedViewController; }
        [vc presentViewController:picker animated:YES completion:nil];
    }
    return self;
}
```

**Comment by Tippit** [comment]
i tried then

I had in CLCustomEffect.m

@implementation CLCustomEffect
{
    UIImage *_blendImage;
 ...   
}


#pragma mark- ImagePicker delegate

- (void)imagePickerController:(UIImagePickerController *)picker didFinishPickingMediaWithInfo:(NSDictionary *)info
{
   _blendImage = [info objectForKey:UIImagePickerControllerOriginalImage];
    
}

- (UIImage*)applyEffect:(UIImage*)image
{
 GPUImagePicture *imageSource = [[GPUImagePicture alloc] initWithImage:image];

...
    GPUImageDissolveBlendFilter *blendFilter = [[GPUImageDissolveBlendFilter alloc]init];

    UIImage *quickFilteredImage = [blendFilter imageByFilteringImage:_blendImage];

}

at runtime I get a crash

Assertion failure in -[GPUImagePicture initWithCGImage:smoothlyScaleOutput:],iOS9/_Demo/CLImageEditorDemo/SDKs/GPUImage/framework/Source/iOS/GPUImagePicture.m:74
2015-08-12 11:06:24.404 MyApp[22255:986445] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Passed image must not be empty - it should be at least 1px tall and wide'

**Comment by yackle** [comment]
Did you write properly also other part? Sample is a minimum code, so it doesn't available by copy and paste.

**Comment by Tippit** [comment]
I checked my code but - (id) initWithSuperView: (UIView *) superview imageViewFrame (CGRect) frame TOOLINFO (CLImageToolInfo *) info

thank you is the right solution

**Comment by yackle** [comment]
?

**Comment by Tippit** [comment]
it’s ok for me Yackle still have the same issue I will review my code :)

Merci beaucoup :))
