### ISSUE TITLE
Landscape mode

### ISSUE THREAD

**Issue by Tippit** [yackle/CLImageEditor#121]
Hi,

What about device rotating Yackle ?

**Comment by RGSSoftware** [comment]
I belive device rotation is not supported, at least as of Dec 23, 2014.  https://github.com/yackle/CLImageEditor/issues/81

**Comment by Tippit** [comment]
I also think but I wanted to make sure. is there anyone could help achieve it?



—
Cordialement, RegardsClaude Bezeaud
