### ISSUE TITLE
How can i use only one Tool

### ISSUE THREAD

**Issue by sohilmultani** [yackle/CLImageEditor#122]
CLImageEditor Is superb demo for Editing image

I am creating camera app. i want to edit image.But My problem is i am use xib and i want to create my own UI For cropping image. How can i use only crop tool,effect tool, effect tool  from your code....

Please replay me.
Thanx in advance.

**Comment by yackle** [comment]
See https://github.com/yackle/CLImageEditor#menu-customization and #82.
