### ISSUE TITLE
Change the size of imageview

### ISSUE THREAD

**Issue by badalpub1991** [yackle/CLImageEditor#123]
Can i change the size of imageview which displayed while edit in photo editor?

**Comment by yackle** [comment]
I don't understand what you mean. Could you tell me in more detail?

**Comment by badalpub1991** [comment]
I want to change the default imageview size when edit mode enable . Means when we click on edit button then cliimageEditor's imageview will be open , i want to change the size of that imageview.  Is i possible to change the size of imageview ?

**Comment by yackle** [comment]
It is not possible by ordinary. You should hack the code by yourself.

**Comment by natedkin** [comment]
badalpub1991, did you get this to work?
