### ISSUE TITLE
iOS 9 causing images in album to appear stretched. 

### ISSUE THREAD

**Issue by JustK2** [yackle/CLImageEditor#124]
Hi! 

We love your library! However since iOS 9 the images have been appear stretched and blurry...is anyone else having this issue? Is there a plan to fix? Of note, we are using this in a production application so we are bummed. Also using it for video selection if that matters. 

Thanks in advance! 
Karolyn 
![img_6389](https://cloud.githubusercontent.com/assets/10579116/11608462/b94205e0-9b1e-11e5-8882-482ead7264ba.PNG)

**Comment by yackle** [comment]
I didn't quite understand what you meant. 

- What's this image picker?
- Why is this picker is related to the editor?
