### ISSUE TITLE
Is it possible to add fullsize imageview in self.view ?

### ISSUE THREAD

**Issue by badalpub1991** [yackle/CLImageEditor#126]
I want to set blur background related to image . so i need to add full size imageview on uiview. so is it possible to add fullsize imageview ?

**Comment by yackle** [comment]
I think it is possible by insertSubview:atIndex:

**Comment by badalpub1991** [comment]
Thanks for Replay . I tried at each place but not able to added it. can you explain bit more ? In which method i have to insert subview ?

**Comment by yackle** [comment]
What have you tried?

**Comment by badalpub1991** [comment]
I have tried this in view did load method .

_backimageview is my imageview.

_backimgvw.frame=CGRectMake(self.view.frame.origin.x, self.view.frame.origin.y, self.view.frame.size.width, self.view.frame.size.height);
    [self.view addSubview:_backimgvw];
    _backimgvw.image=self.imageView.image;
    _backimgvw.backgroundColor=[UIColor redColor];
I have also tried with insertsubview at index 
also tried 
    [self.view insertSubview:_backimgvw aboveSubview:self.imageView];

but not working.

**Comment by yackle** [comment]
What does self mean?

```
[editor.view insertSubview:_backimgvw atIndex:0];
```

it is working
