### ISSUE TITLE
How to set navigation barTintColor?

### ISSUE THREAD

**Issue by DimonDeveloper** [yackle/CLImageEditor#131]
I try almost everything, but wherever I wrote 
```navigationBar.barTintColor = [UIColor whiteColor];```
or
```[self.navigationController.navigationBar setBarTintColor:[UIColor **whiteColor]];```
or even
```[[UINavigationBar appearance] setBarTintColor:[UIColor whiteColor]];```
 it does nothing.

Please tell me how to do it?

**Comment by yackle** [comment]
As far as I tried,

```
[[UINavigationBar appearance] setBarStyle:UIBarStyleBlack];
[[UINavigationBar appearance] setBarTintColor:[UIColor redColor]];
[[UINavigationBar appearance] setTintColor:[UIColor whiteColor]];
```

works with demo project.

![a](https://cloud.githubusercontent.com/assets/3434935/13209829/089600d4-d96c-11e5-873d-189dcafc753b.png)

**Comment by DimonDeveloper** [comment]
Now works fine, thank you very much.
