### ISSUE TITLE
swift integration 

### ISSUE THREAD

**Issue by nsoud** [yackle/CLImageEditor#139]
hi,
Please i need your help to integrate into swift code in a very easy way, with clear steps.
Thank you very much for your help

**Comment by yackle** [comment]
I'm not sure what do you want to do

**Comment by binitaModi** [comment]
I need CLImageEditor in swift , Any one help me?

**Comment by yackle** [comment]
see #163

**Comment by binitaModi** [comment]
I know about this answer , but my requirement changes in Image Editing controller as per client requirement , So its require in swift language.

**Comment by vitalys** [comment]
1) You can write your own swift implementation using this library as example
2) You can pay someone who can write swift implementation
