### ISSUE TITLE
Enable Disable Certain Editing Options, Add Custom Stickers

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [yackle/CLImageEditor#140]
I want to enable or disable certain editing options appears bottom of screen.

Like, I want Rotate, Crop, Resize options to not appear in the editing options.

Or, even I want to add my own option, say ''Choose from gallery'' in the list appears in bottom of screen.

So, how can I do that?

**Comment by yackle** [comment]
see README and closed issues (e.c. #82)
