### ISSUE TITLE
i want to add Lomo filter to SDK.

### ISSUE THREAD

**Issue by pvni** [yackle/CLImageEditor#143]
i want  to customize the filters .Like adding some extra filters Lomo,vintage etc..Please explain how can i 
implement extra filters in SDK.

Please check screenshot.I have added limo into list .But not able to add the effect.

**Comment by yackle** [comment]
What do you want to know in particular? I think that other issues (e.g. #18, #68) would be helpful.

**Comment by pvni** [comment]
Thanks for reply,
When I added a new file ,Im getting below issue.


Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_CLFilterBase", referenced from:
      _OBJC_CLASS_$_CLLomoFilters in CLLomoFilters.o
  "_OBJC_METACLASS_$_CLFilterBase", referenced from:
      _OBJC_METACLASS_$_CLLomoFilters in CLLomoFilters.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by pvni** [comment]
Thank you very much for help. It's working
