### ISSUE TITLE
Handle navigation button events. e.g. Back, Done

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [yackle/CLImageEditor#144]
Hello,

I've added custom thumbnail in the horizontal slider called "Add Image". After clicking added two new thumbnails called "from gallery", "camera".

But when I press the Back button from the navigation panel, the horizontal slider remains the same means it doesn't go back to its previous state.

So, I want to handle back and done button action.

Thanks!

**Comment by yackle** [comment]
I think you should remove the horizontal slider in `-(void)cleanup`.

**Comment by Rashesh-Bosamiya** [comment]
Would you please explain, what code do I need to put inside this method in order to remove horizontal slider.

**Comment by yackle** [comment]
I'm not sure you want to do. Can I see your code?
