### ISSUE TITLE
iOS 10 compatibility

### ISSUE THREAD

**Issue by Tippit** [yackle/CLImageEditor#145]
Hi,

With Xcode 8 and iOS 10 the filters are not showing in the toolbar and the app freezes, all of the other tools are working well!

Could you help to fix this please

**Comment by yackle** [comment]
I can't reproduce it.

![2016-07-08 7 33 01](https://cloud.githubusercontent.com/assets/3434935/16672056/7b253196-44de-11e6-8e8a-8a52d50447ee.png)
