### ISSUE TITLE
CLStickerView

### ISSUE THREAD

**Issue by SwamyChunchu** [yackle/CLImageEditor#159]
how can we add another StickerTool

**Comment by yackle** [comment]
see [README](https://github.com/yackle/CLImageEditor#sticker-tool) or other closed issues.

**Comment by SwamyChunchu** [comment]
hello sir,good evening.
     after clicking the OK or Done button how can we re-edit   the image is
any possible to undo  that image.

**Comment by SwamyChunchu** [comment]
hello sir good morning.

       we have one sticker tool na i need to add  two more tool like stiker
tool.
how can we add customly.


could you tell me please, and is there any undo option.




thanking you and its very usefull..awesome creativity.
