### ISSUE TITLE
"_OBJC_CLASS_$_CLImageEditor", referenced from:

### ISSUE THREAD

**Issue by CeoRain** [yackle/CLImageEditor#160]
Hello, I was trying to make a small demo.

I #import "CLImageEditor.h" and then i go like

`CLImageEditor *editor = [[CLImageEditor alloc] initWithImage:[UIImage mageNamed:@"TGoodImage"]];

editor.delegate = self;

   [self presentViewController:editor animated:YES completion:nil];`

And I'm getting two error, 
1. Undefined symbols for architecture x86_64:  "_OBJC_CLASS_$_CLImageEditor", referenced from:
2.  linker command failed with exit code 1 (use -v to see invocation)

**Comment by yackle** [comment]
how did you link this library?

**Comment by CeoRain** [comment]
Hello, thanks for responding. I link this library by #import

**Comment by yackle** [comment]
I think #import is nothing to do. I mean how did you add the library to your project. Can I see your project?
