### ISSUE TITLE
Is there anyway to hide the default effects/editors?

### ISSUE THREAD

**Issue by ihpalash** [yackle/CLImageEditor#164]
There are a lot of effects and editors in my app when I added the CLI. Is there anyway to hide some of the effetcts from the app UI??

**Comment by yackle** [comment]
See [README](https://github.com/yackle/CLImageEditor#customizing).

**Comment by ihpalash** [comment]
Hello this is how I am showing all the effects:

```
+ (CGFloat)defaultDockedNumber
{
    // Image tools are sorted according to the dockedNumber in tool bar.
    // Override point for tool bar customization
    NSArray *tools = @[
                       @"CLFilterTool",
                       @"CLBrightnessTool",
                       @"CLSaturationTool",
                       @"CLContrastTool",
                       @"CLEffectTool",
                       @"CLBlurTool",
                       @"CLRotateTool",
                       @"CLClippingTool",
                       @"CLToneCurveTool",
                       @"CLSplashTool",
                       @"CLFramesTool",

                       ];
```

Problem is that when I comment out one of the code or delete one of the code. They dont disappear. 

Can you please tell me what am I doing wrong?? I just want to hide couple of filters, effects.

**Comment by yackle** [comment]
Did you read README?

```
CLImageToolInfo *tool = [editor.toolInfo subToolInfoWithToolName:@"CLFilterTool" recursive:NO];
tool.available = NO;

tool = [editor.toolInfo subToolInfoWithToolName:@"CLEffectTool" recursive:NO];
tool.available = NO;
```

**Comment by ihpalash** [comment]
yes. But what does it mean?

**Comment by yackle** [comment]
Sorry, I'm not sure what do you want to do. What is the problem?

**Comment by ihpalash** [comment]
I just want to hide couple of the effects . for example I want to hide CLsplashtool and CLblurtool. Can I do that?

**Comment by yackle** [comment]
So did you try above code?
