### ISSUE TITLE
QUESTION: Where to park your custom tool source codes?

### ISSUE THREAD

**Issue by hollowaykeanho** [yackle/CLImageEditor#167]
I'm aware of Issue #82; my goal is to create a tool that offers an option to delete the selected image from local storage. 

The class inheritance is straightforward but where do we park our new classes?  I'm installing via Cocoapods so modifying CLImageEditor module directly is not desirable.

**Comment by yackle** [comment]
Please use

```
pod 'CLImageEditor/Dev'
```
