### ISSUE TITLE
Can I change the color of navigation bar and background view color in ios .

### ISSUE THREAD

**Issue by GowthamYadav2105** [yackle/CLImageEditor#171]

**Comment by yackle** [comment]
yes you can

**Comment by GowthamYadav2105** [comment]
Please provide sample code or any helping link

**Comment by GowthamYadav2105** [comment]
Actually could not able customise  the UI and Sharpen , fade , Saturation options are not able , pls consider as high priority and respond as ASAP

**Comment by yackle** [comment]
see demo.

https://github.com/yackle/CLImageEditor/blob/master/Demo/CLImageEditorDemo/CLImageEditorDemo/ViewController.m

For example, you can setting the theme by using commented out lines on `viewDidLoad`.
