### ISSUE TITLE
What's wrong with the CLStickerTool

### ISSUE THREAD

**Issue by LhiKien** [yackle/CLImageEditor#173]
I use the custom sticker images bundle, and move the demo to a new project.
The close button and rotation button are both in wrong place.
Can anybody tell me why? Thanks a lot!

![simulator screen shot 2017 3 17 5 01 33](https://cloud.githubusercontent.com/assets/6253031/24019217/27b37300-0ad2-11e7-8bce-1e05bb27828f.png)
![simulator screen shot 2017 3 17 5 32 34](https://cloud.githubusercontent.com/assets/6253031/24019524/4ce0c79e-0ad3-11e7-961d-4fdc1679a312.png)
![simulator screen shot 2017 3 17 5 33 21](https://cloud.githubusercontent.com/assets/6253031/24019525/4d29dbd2-0ad3-11e7-8056-09f29ec12576.png)

**Comment by yackle** [comment]
I couldn't reproduce the issue. Could you please tell me more details or steps?

**Comment by LhiKien** [comment]
Thanks for your attention!
The issue is solved. I found the cause of the problem.
I used UIView (Extension) in the new project.
If I remove the extension of the UIView, CLImageEditor will run in correct.

**Comment by yackle** [comment]
👍
