### ISSUE TITLE
UIAlertView deprecated in iOS 9, 10

### ISSUE THREAD

**Issue by cliffjoyce** [yackle/CLImageEditor#175]
It would be great if CLImageEditorViewController could test for the availability of UIAlertViewController and use that API instead of the deprecated UIAlertView.  This is noticeable in apps targeting iOS 9.0+.

Thanks so much for this great library.

**Comment by yackle** [comment]
Thank you for your advice.
In above commit, UIAlertView replaced with UIAlertController.

**Comment by cliffjoyce** [comment]
Thank you!
