### ISSUE TITLE
[Swift 3] Navigation Left & Right Buttons Hidden but Functional When Using Tools

### ISSUE THREAD

**Issue by Lwdthe1** [yackle/CLImageEditor#179]
I managed to make the navigation bar items show in the view with the carousel of tools to pick from, but when I choose a tool to edit my image, the left and right buttons in the navigation bar are hidden  even though I can click on them. I am pushing the view controller instead of presenting it.

![2017-04-30](https://cloud.githubusercontent.com/assets/5778798/25569194/2cefafe2-2de0-11e7-930c-2de213fa1a6e.png)
---

---

---
![2017-04-30 1](https://cloud.githubusercontent.com/assets/5778798/25569192/2bdd1a90-2de0-11e7-9301-97d4b93e6816.png)

**Comment by yackle** [comment]
Does that mean you made any changes?

**Comment by Lwdthe1** [comment]
We found the issue. We had `UINavigationBar.appearance().tintColor = .whiteColor()` for our app's navigation bar, so changing it to `UINavigationBar.appearance().tintColor = .blackColor()` fixes the problem.
