### ISSUE TITLE
GPUImage Support?

### ISSUE THREAD

**Issue by ChristopherDoherty** [yackle/CLImageEditor#18]
Hello,

Has anyone got any idea how to implement GPUImage [https://github.com/BradLarson/GPUImage] as an Optional ImageTool for more advanced image filters and manipulations. I've been trying for the last week to implement this feature, to little success.

Any response is greatly appreciated.

Christopher

**Comment by sohilmultani** [comment]
Hello i am adding GPUImage in my project but i can't add "CLGPUImageVignetteFilter" .

I am adding this code 

#import "CLFilterBase.h"

+ (NSDictionary*)defaultFilterInfo
{
            @"CLGPUImageVignetteFilter"    : @{@"name":@"CLGPUImageVignetteFilter",         @"title":[CLImageEditorTheme localizedString:@"CLGPUImageVignetteFilter_DefaultTitle" withDefault:@"Vignette"],     @"version":@(6.0), @"dockedNum":@(14.0)}

}


@interface CLGPUImageVignetteFilter : CLDefaultEmptyFilter
@end
@implementation CLGPUImageVignetteFilter
@end


the output image is nill.

Can you explain step by step please how to add  "CLGPUImageVignetteFilter"

Thank you.
