### ISSUE TITLE
Resize Tool

### ISSUE THREAD

**Issue by Mavrixsolutions** [yackle/CLImageEditor#180]
Hi, Dont know how end tool of resize settings works.
when user tapp is show horizontal and vertical. i save both images but no effect any image.
kindly tell us how it works.
Thanks

**Comment by yackle** [comment]
If horizontal/vertical button selected, new image width/height will be set to value that tapped button has. Width and height values are not swapped when switch horizontal/vertical button.

**Comment by Mavrixsolutions** [comment]
Thanks for quick response yackle.
