### ISSUE TITLE
Navigation bar for tools overlaps with status bar

### ISSUE THREAD

**Issue by javaboyjunior** [yackle/CLImageEditor#186]
Hi there

Trying to figure out why the buttons for editing tools appear overlapped with the status bar. The main CLImageViewController is fine - it's all the child windows. I can't see any different between my app and the demo although clearly there is something. 

Ideas much appreciated.

Thanks

Mike

![img_0716](https://user-images.githubusercontent.com/522857/28340984-9a39e0a8-6bc6-11e7-87f9-59675e85f492.PNG)

**Comment by yackle** [comment]
Can I get a minimum sample project that can confirm this issue?

**Comment by m4f1h4rd** [comment]
I have the same issue.
Can I hide status bar?
![simulator screen shot - iphone se - 2017-10-24 at 20 27 52](https://user-images.githubusercontent.com/17106759/31958416-5cde2580-b8fa-11e7-901e-c81f2e5756cd.png)

**Comment by ghyzx** [comment]
Sometimes it will appear this circumstance. The occurrence probability is very big when take photos from the camera.

**Comment by m4f1h4rd** [comment]
In my project I disabled the status bar. And it appear only in CLImageEditor Controller.

**Comment by yackle** [comment]
Please try 18c1efe and

```
[[CLImageEditorTheme theme] setStatusBarHidden:YES];
```

**Comment by ghyzx** [comment]
Thanks yackle, but the problem still exists.
![123](https://user-images.githubusercontent.com/5229158/33946222-2a7378a0-e05c-11e7-8398-9ae281a71c77.jpg)

**Comment by yackle** [comment]
@ghyzx Is that the problem is the status bar is displayed (or collapse of the layout)?

**Comment by ghyzx** [comment]
@yackle  The status bar and navigation bar are overlap partly.

**Comment by yackle** [comment]
Does anyone know of a way to reproduce this issue?

**Comment by ghyzx** [comment]
my steps is as follows
take photo from the camera on iPhone 7 with iOS 11.1

**Comment by yackle** [comment]
I couldn't reproduce this issue with my device. Can I get sample project that reproduce the issue?

**Comment by jianyaoang** [comment]
Not sure if my encounter is the same with everyone else. But I was facing the same issue and I solved it by showing the status bar. 

**Issue I faced:**
1. ViewController A has hidden status bar in viewDidAppear
2. ViewController A presents CLImageEditor (theme is set to not hide status bar)
3. ViewController A viewWillDisappear sets hidden status bar to false
4. Overlapping issue as shown by screenshots above happened.

**How I solved it:**
Before ViewController A is to present CLImageEditor, set hidden status bar to false. Call `[self setNeedsStatusBarAppearanceUpdate];`, and that shall call `(BOOL)prefersStatusBarHidden`

**Clues that helped me solve this:**
Found this part of code in `CLImageEditorViewController`, 
```        
CGFloat dy = ([[[UIDevice currentDevice] systemVersion] floatValue]<7) ? 0 : MIN([UIApplication sharedApplication].statusBarFrame.size.height, [UIApplication sharedApplication].statusBarFrame.size.width);
```

When statusBar is hidden the `[UIApplication sharedApplication].statusBarFrame.size.height`  will be zero, and then the setting of constraints to top will be zero as well.

Hope that helps!

**Comment by shripadkulkarid** [comment]
How to solve this issue in swift

**Comment by zhangao0086** [comment]
> Not sure if my encounter is the same with everyone else. But I was facing the same issue and I solved it by showing the status bar.
> 
> **Issue I faced:**
> 
> 1. ViewController A has hidden status bar in viewDidAppear
> 2. ViewController A presents CLImageEditor (theme is set to not hide status bar)
> 3. ViewController A viewWillDisappear sets hidden status bar to false
> 4. Overlapping issue as shown by screenshots above happened.
> 
> **How I solved it:**
> Before ViewController A is to present CLImageEditor, set hidden status bar to false. Call `[self setNeedsStatusBarAppearanceUpdate];`, and that shall call `(BOOL)prefersStatusBarHidden`
> 
> **Clues that helped me solve this:**
> Found this part of code in `CLImageEditorViewController`,
> 
> ```
> CGFloat dy = ([[[UIDevice currentDevice] systemVersion] floatValue]<7) ? 0 : MIN([UIApplication sharedApplication].statusBarFrame.size.height, [UIApplication sharedApplication].statusBarFrame.size.width);
> ```
> When statusBar is hidden the `[UIApplication sharedApplication].statusBarFrame.size.height` will be zero, and then the setting of constraints to top will be zero as well.
> 
> Hope that helps!

Exact!

@yackle Here is a sample project:
[CLImageEditor-master.zip](https://github.com/yackle/CLImageEditor/files/2413659/CLImageEditor-master.zip)

# Current Behavior
`CLImageEditorTheme.theme.statusBarHidden = YES;`

<img width="50%" src="https://user-images.githubusercontent.com/7742344/45991587-2ca00480-c0b8-11e8-930c-f02ccce1529e.png">

`CLImageEditorTheme.theme.statusBarHidden = NO;`
<img width="50%" src="https://user-images.githubusercontent.com/7742344/45991588-2f025e80-c0b8-11e8-90ce-e2f53d08e68b.jpeg">


# Steps to Reproduce:
1. Open and run the project: `Demo/CLImageEditorDemo/CLImageEditorDemo.xcodeproj`
2. Click the `Edit` button on the bottom bar

**Comment by yackle** [comment]
Thanks @all 
I think this issue is fixed by #218, please check it.

**Comment by zhangao0086** [comment]
👍

**Comment by Indolia** [comment]
Hi Team,
is any option to write text on image?
