### ISSUE TITLE
Manual Bundle "Drag and Drop" Source File Directory Failure

### ISSUE THREAD

**Issue by HackShitUp** [yackle/CLImageEditor#187]
Xcode can't find multiple source files in CLImageEditor when it's implemented manually. I'm aware that the README instructed to drag and drop the source files from the demo into the Xcode project. (I'm not doing this via Cocoapods for personal reasons). Whenever I drag the project files (including the bundle) I persistently get an error saying that CLImageEditorViewController.h/.m is missing. Any ideas?

**Comment by yackle** [comment]
Have you checked `Create groups`?

**Comment by HackShitUp** [comment]
@yackle sorry, how do you mean by that?

**Comment by HackShitUp** [comment]
@yackle Thanks, I resolved this issue by adding the files with the "Create Groups" option!
