### ISSUE TITLE
An Android version by Crowdfunding?

### ISSUE THREAD

**Issue by codenia** [yackle/CLImageEditor#194]
Dear Sho Yakushiji, this is a very good library. Great work. It works perfectly. 
Since the photo Image Editor UI has been discontinued in the Adobe Creative SDK, many developers are looking for alternatives.
Your editor is the perfect replacement for iOS. What do you think of starting a crowdfunding campaign to develop a version for Android? I would like to support the campaign.
Thanks again for this image editor library.

**Comment by yackle** [comment]
I'm happy in being able to hear that you liked this editor. But I have no plans to develop an Android version, because I don’t know much about Android development. I'm sorry I couldn't be of any help, but I think it's better to find Android developers. 
Thanks.
