### ISSUE TITLE
CLTextTool landscape keyboard

### ISSUE THREAD

**Issue by cliffjoyce** [yackle/CLImageEditor#196]
Using the 2017-10-18 build, the CLTextTool does not properly handle the keyboard in landscape orientations (the portrait keyboard always appears instead of the landscape keyboard).

To reproduce the issue:  build the CLImageEditorDemo with Xcode 9 and launch the iPad Simulator in landscape orientation;  tap the Edit button;  tap the Text tool;  tap the New button.

I think the issue is line 618 of _CLImageEditorViewController, because if I change line 618 to unconditionally return UIInterfaceOrientationMaskAll, then the landscape keyboard appears as expected.

A related issue: there's a UITextField that appears on screen while text is being typed.  In the attached screenshot, you can see its blue insertion point just above the New button.

![texttool-orientation-issue](https://user-images.githubusercontent.com/266027/31842522-5fd4728a-b5a3-11e7-81cf-9c0be43cf3ef.png)

**Comment by yackle** [comment]
Thanks for reporting!
