### ISSUE TITLE
Filter takes time to apply

### ISSUE THREAD

**Issue by pinkal** [yackle/CLImageEditor#199]
Hi, such a nice library for image editing.
I am facing one issue, While image edit with "Filter" option, it's taking time to apply selected filter on image(about 1 min). can you help me with this?

Thanks in advance

**Comment by vvit** [comment]
You should provide, OS version, device version, any filter information.

**Comment by pinkal** [comment]
it's not working with iOS 11
i have attached screenshot 


![simulator screen shot - iphone x - 2017-11-09 at 11 01 07](https://user-images.githubusercontent.com/2765128/32590865-a590ed04-c542-11e7-8963-7dbc2275d989.png)

**Comment by Tippit** [comment]
Simulator ?

Cordialement,
Claude Bezeaud.

**Comment by Tippit** [comment]
On real device it’s working like a charm

Cordialement,
Claude Bezeaud.

**Comment by yackle** [comment]
The processing of filter tool is very heavy in the simulator. Please try with real device.
