### ISSUE TITLE
Unable to sort custom stickers

### ISSUE THREAD

**Issue by albertbori** [yackle/CLImageEditor#201]
Consider the following code:

    stickerTool.optionalInfo["stickerPath"] = Bundle.main.resourcePath! + "/CLIImageEditorAssets/Stickers/"

There is no way to guarantee the order that the stickers display when presented in the Sticker tool. It should default to alphabetical by file-name.

**Comment by Tippit** [comment]
Thank's 💯

**Comment by yackle** [comment]
thanks
