### ISSUE TITLE
Change Editor Option Button Size

### ISSUE THREAD

**Issue by aly-irshad** [yackle/CLImageEditor#203]
Hello,
Can anyone suggest me how to change the size of bottom editor button? I am able to change images for them but how can I change height. I tried to change **kMenuBarHeight**, it reduces the height but the button goes down to the screen and are not fully visible, the text gets cut down. Please suggest.

**Comment by yackle** [comment]
Please modify `initWithFrame:` of `CLToolbarMenuItem`.
