### ISSUE TITLE
How can I get a clear background when the image is rotated ?

### ISSUE THREAD

**Issue by sriteja25** [yackle/CLImageEditor#204]
When I apply rotate option I get the whitespaces at the remaining area. How can I get a transparent rotated image. ?

![img_37fdb6f4c091-1](https://user-images.githubusercontent.com/12974407/33872910-4474980c-df5c-11e7-9161-257f9ba24449.jpeg)

**Comment by yackle** [comment]
Rotate tool makes a transparent image, but was it different?

<img width="471" alt="2018-01-10 13 01 02" src="https://user-images.githubusercontent.com/3434935/34755334-c26a41ba-f606-11e7-8ad8-71043b46865c.png">
