### ISSUE TITLE
Distorted custom sticker images

### ISSUE THREAD

**Issue by albertbori** [yackle/CLImageEditor#206]
![screen shot 2017-12-18 at 4 38 30 pm](https://user-images.githubusercontent.com/1742709/34133459-08c1d33c-e412-11e7-96c0-06c2eb0c6f47.png)

In CLSTickerTool.m, in `setStickerMenu`, the line `view.iconImage = [image aspectFit:CGSizeMake(50, 50)];` causes the sticker to attempt to be aspect Fit, but in CLToolbarMenuItem, the iconImageView is set to UIViewContentModeScaleAspectFill, which causes the stickers that are not perfectly square to be pixelated and clipped as in the image above.

**Comment by yackle** [comment]
Merged #207, thanks!
