### ISSUE TITLE
NSLayoutConstraint warnings in 0.2.2

### ISSUE THREAD

**Issue by mjswan** [yackle/CLImageEditor#209]
Just updated to version 0.2.2 to fix issue #195. Using Xcode 9.2 and using a Deployment Target of iOS 9.3, I'm getting a lot (91) of build warnings of the form:

```
<mypath/to/product>/Pods/CLImageEditor/CLImageEditor/ViewController/_CLImageEditorViewController.m:190:12: warning: 'NSLayoutConstraint' is partial: introduced in iOS 6.0 [-Wunguarded-availability]
+(NSArray <NSLayoutConstraint *>*)setConstraintsLeading:(NSNumber *)leading
           ^
In module 'UIKit' imported from <mypath/to/product>/Pods/Target Support Files/CLImageEditor/CLImageEditor-prefix.pch:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/NSLayoutConstraint.h:96:12: note: 'NSLayoutConstraint' has been explicitly marked partial here
@interface NSLayoutConstraint : NSObject
           ^
```

These are warnings and the library still builds and works but it would be great to eliminate the warnings. BTW, thanks for building such a great library!

**Comment by yackle** [comment]
I couldn't find warnings using same settings. Did Clean project  not work?

**Comment by mjswan** [comment]
Clean project did not change the production of warnings.

**Comment by mjswan** [comment]
It was easy to reproduce the warnings:
1. Create a new iOS Single View App Obj-C project in Xcode 9.2
2. Set the Deployment Target to 9.3 in Targets>General
3. Close project
4. pod install 'CLImageEditor'
5. Open the new .xcworkspace
6. Attempt to comple/run

[CLDrawToolSample.zip](https://github.com/yackle/CLImageEditor/files/1711789/CLDrawToolSample.zip)

**Comment by yackle** [comment]
@mjswan What version of cocoapods do you use? In `1.2.1`, such warnings do not appear.

**Comment by mjswan** [comment]
'pod --version' produces '1.3.1'.

I'm closing this issue since seemingly spontaneously Xcode asked me to update the CLImageEditor pod project to the latest settings. Once I updated the project, all the warnings went away. I don't know what happened to trigger the update request. @yackle : thank you for your interest.

**Comment by yackle** [comment]
NP 👍
