### ISSUE TITLE
Multiple warnings regarding implicitly retaining self

### ISSUE THREAD

**Issue by colincameron** [yackle/CLImageEditor#211]
Environment:
- Xcode 9.2
- iOS app targeting iOS 9, base SDK iOS 11.2
- CLImageEditor installed via Cocoapods

When building an app using CLImageEditor, I can see 105 warnings, for example:
> /Users/colin/git/[...]/Pods/CLImageEditor/CLImageEditor/ViewController/_CLImageEditorViewController.m:390:85: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior

Just in `_CLImageEditorViewController.m`, there are dozens of warnings:

![screenshot 2018-03-29 12 41 51](https://user-images.githubusercontent.com/1846118/38090228-d4b51e72-3359-11e8-9f45-8f4579dcceeb.png)

**Comment by yajra** [comment]
@colincameron were you able to fix this warnings? TIA

**Comment by colincameron** [comment]
No I'm just ignoring the warnings for now, as I don't want to start editing files pulled from Cocoapods. I'll probably open a PR to fix this.

**Comment by colincameron** [comment]
Opened PR #214

**Comment by colincameron** [comment]
Seems to be working fine for me on Xcode 9.4.1 - not sure what the problem could be sorry.

**Comment by yajra** [comment]
@colincameron I just tried recompiling on XCode 9.4 and it works well now. Must be some issue on my environment. Thanks!
