### ISSUE TITLE
Required photo ratio after editing

### ISSUE THREAD

**Issue by alecgorge** [yackle/CLImageEditor#42]
I would like to force my users to crop their photo to one of the specified sizes defined in the `ratios` key of `CLClippingTool`'s `optionalInfo` dictionary.

What the best way of going around this? Should I make a custom subtool that based off of CLClippingTool?

Is there any way to prevent the user from selecting done from a subtool?

**Comment by andrew8712** [comment]
That would be a great feature though.

**Comment by michaelbina** [comment]
I need this as a feature for my app as well.  Can anyone think of a workaround to make it possible to force the user to crop the photo to a specific ratio while editing?
