### ISSUE TITLE
Bug in iOS 8 when run CLImageEditor from landscape mode.

### ISSUE THREAD

**Issue by DimonDeveloper** [yackle/CLImageEditor#81]
![ios simulator screen shot dec 20 2014 1 44 29 pm](https://cloud.githubusercontent.com/assets/3527457/5514682/982410b2-884e-11e4-80af-750db8278d4b.png)

Done button beyond the screen and imageview off-center

**Comment by patelmayank** [comment]
+1

**Comment by Tippit** [comment]
+1

**Comment by grapto** [comment]
+1

**Comment by gavla** [comment]
+1

**Comment by gavla** [comment]
If you embed in a UINavigation controller before before presenting CLImageEditor it will control the rotation for you and fix this issue you just have to change shouldAutorotate to YES like below

     - (BOOL)shouldAutorotate
    {
        return YES;
    }

In CLImageEditor.m

**Comment by yackle** [comment]
please try #183 changes.

**Comment by phanibob7** [comment]
For this we need to make the presenting view controller portrait before presenting editor.

        let value = UIInterfaceOrientation.portrait.rawValue
        UIDevice.current.setValue(value, forKey: "orientation")
