### ISSUE TITLE
Custom Effects

### ISSUE THREAD

**Issue by Tippit** [yackle/CLImageEditor#84]
I have create a new class from CLEffect to implement a tool to blend two image, i would like the user to open photo library  to select an image or take one with camera and blend it with the one opened in Editor.

My question is: from where (in code) can i make a call to UIImagePickerController?

is it from CLEffect, CLEffectBase or CLEffectTool.

Please help

**Comment by yackle** [comment]
I do not know because it is not tried. I think from your custom effects maybe.
