### ISSUE TITLE
Image preview in toolbar

### ISSUE THREAD

**Issue by Tippit** [yackle/CLImageEditor#85]
is it possible to have image filtered preview in Effect toolbar as we get in Filter toolbar?

**Comment by yackle** [comment]
you can do it, if you try.

**Comment by Tippit** [comment]
Already tryed but i will try again :(Sent using CloudMagicOn jeu., janv. 15, 2015 at 02:46,  yackle/CLImageEditor <reply@reply.github.com> wrote:            you can do it, if you try.

**Comment by natedkin** [comment]
Tippit, did you get this to work?

**Comment by Tippit** [comment]
Not yet sorry
