### ISSUE TITLE
Crash with iPhone 4

### ISSUE THREAD

**Issue by Tippit** [yackle/CLImageEditor#86]
Some users have reported a crash when using blur tool on iPhone 4, and on iPhone 5/6 blur tool sometimes is very long to apply effect with big image (retina).
I have modified the blurLevel value           
 int boxSize = (int)(blurLevel * 0.9 * MIN(self.size.width, self.size.height));
The default value 0.1 is not suffisant to get a perfect effect 
with blurLevel 0.9 the memory take about 150MO!

**Comment by yackle** [comment]
ok, thanks for reporting!
