### ISSUE TITLE
Crash when applied multiple filters

### ISSUE THREAD

**Issue by Tippit** [yackle/CLImageEditor#89]
when you apply more than one or two Filters or Effects sometimes the app crash, this append on iPad Air and iPhone 6. What's happened, memory leaks, bad memory management or iDevice RAM inadequate?

It's very, very frustrating and annoying for the users...

**Comment by Tippit** [comment]
Fix
http://stackoverflow.com/questions/26163018/bsxpcmessage-received-error-for-message-connection-interrupted-on-cicontext-wit

**Comment by yackle** [comment]
thx!
