### ISSUE TITLE
App Rejected 2.23

### ISSUE THREAD

**Issue by mohitpopat** [yackle/CLImageEditor#93]
Hello,

i have used CLImageEditor in my one App and app is rejected with following reason.

please help me and let me know how to fix this.

2.23 - Apps must follow the iOS Data Storage Guidelines or they will be rejected
----- 2.23 -----

We found that your app does not follow the iOS Data Storage Guidelines, which is required per the App Store Review Guidelines.

In particular, we found that on launch and/or content download, your app stores 2.75MB. To check how much data your app is storing:

- Install and launch your app
- Go to Settings > iCloud > Storage & Backup > Manage Storage 
- If necessary, tap "Show all apps" 
- Check your app's storage

The iOS Data Storage Guidelines indicate that only content that the user creates using your app, e.g., documents, new files, edits, etc., should be backed up by iCloud. 

Temporary files used by your app should only be stored in the /tmp directory; please remember to delete the files stored in this location when the user exits the app.

Data that can be recreated but must persist for proper functioning of your app - or because customers expect it to be available for offline use - should be marked with the "do not back up" attribute. For NSURL objects, add the NSURLIsExcludedFromBackupKey attribute to prevent the corresponding file from being backed up. For CFURLRef objects, use the corresponding kCFURLIsExcludedFromBackupKey attribute. 

Thanks
Mohit Popat

**Comment by yackle** [comment]
I think this library doesn't use the storage. Why do you think the library causes the reject?
