### ISSUE TITLE
Optional tools not being displayed.

### ISSUE THREAD

**Issue by ToddHoff** [yackle/CLImageEditor#94]
I'm trying to configure the sticker tool and the text tool into the menu, but I don't see them displayed. I exclude some tools and change the ordering of others and that seems to work. Is there anything else I need to do?

CLImageEditor *editor = [[CLImageEditor alloc] initWithImage:image];

 CLImageToolInfo *text_tool = [editor.toolInfo subToolInfoWithToolName:@"CLTextTool" recursive:NO];
   text_tool.available = YES;

 CLImageToolInfo *sticker_tool = [editor.toolInfo subToolInfoWithToolName:@"CLStickerTool" recursive:NO];
    sticker_tool.optionalInfo[@"stickerPath"] = @"stickers.bundle";
    sticker_tool.available = YES;

**Comment by yackle** [comment]
How did you install this library? If cocoapods, you need to add following lines.

```
pod 'CLImageEditor/StickerTool'
pod 'CLImageEditor/TextTool'
```

**Comment by ToddHoff** [comment]
No I did not. Thanks, that worked.

**Comment by yackle** [comment]
:+1:
