### ISSUE TITLE
How do you manage stickers?

### ISSUE THREAD

**Issue by ToddHoff** [yackle/CLImageEditor#95]
The sticker example says to pass in the directory name where the stickers are located. Looking at the source code the images are not in a bundle, they are accessed via the file manager. The problem I'm having is I'm not sure how to preload stickers so they will be available in a directory. Do you have any example code on how to do that? I researched for a bit and I didn't come up with anything. 

I apologize if this is the wrong venue for such questions, but I didn't see anywhere else to ask.

thanks

**Comment by yackle** [comment]
How about #43

**Comment by ToddHoff** [comment]
That did it, thanks. BTW, your code is very clean and clear. It's a pleasure to read.

**Comment by yackle** [comment]
That's good, thx :laughing:
